# Generated by Django 5.2.17 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocopy', '0013_alter_image_image_alter_template_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The link will be available at /copy/r/&lt;slug&gt;/.', max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('destination_url', models.CharField(help_text='A site path or absolute URL to redirect visitors to.', max_length=2048)),
            ],
        ),
    ]
