# Generated by Django 6.0 on 2025-12-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocopy', '0013_alter_image_image_alter_template_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnavbar',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnavbar',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='historicalpage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpage',
            name='template',
        ),
        migrations.DeleteModel(
            name='HistoricalCopy',
        ),
        migrations.DeleteModel(
            name='HistoricalNavbar',
        ),
        migrations.DeleteModel(
            name='HistoricalPage',
        ),
    ]
