# Generated by Django 5.2.17 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocopy', '0014_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='country_code',
            field=models.CharField(blank=True, help_text="Country derived from the visitor's IP address", max_length=2),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='city',
            field=models.CharField(blank=True, help_text="City derived from the visitor's IP address", max_length=255),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='organization',
            field=models.CharField(blank=True, help_text="Network/ISP that owns the visitor's IP address", max_length=255),
        ),
    ]
